name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        working-directory: backend
        run: ./mvnw clean package -DskipTests